name = "Hugo Clean Blog"
license = "Apache 2.0"
licenselink = "https://github.com/go-zen-chu/hugo-clean-blog-theme/blob/master/LICENSE.md"
description = "Hugo Clean Blog Theme"
homepage = "https://github.com/go-zen-chu/hugo-clean-blog-theme"
tags = ["blog", "bootstrap"]
features = ["blog", "bootstrap"]
min_version = 0.18

[author]
  name = "Akira Masuda"
  homepage = "https://amasuda.xyz"

# original theme
[original]
  name = "Startbootstrap Clean Blog"
  homepage = "http://startbootstrap.com/template-overviews/clean-blog/"
  repo = "https://github.com/BlackrockDigital/startbootstrap-clean-blog"
